set_property PACKAGE_PIN   M21   [ get_ports "ddr4_adr[0]" ]
set_property PACKAGE_PIN   N21   [ get_ports "ddr4_adr[1]" ]
set_property PACKAGE_PIN   E20   [ get_ports "ddr4_adr[2]" ]
set_property PACKAGE_PIN   P21   [ get_ports "ddr4_adr[3]" ]
set_property PACKAGE_PIN   E21   [ get_ports "ddr4_adr[4]" ]
set_property PACKAGE_PIN   E19   [ get_ports "ddr4_adr[5]" ]
set_property PACKAGE_PIN   M22   [ get_ports "ddr4_adr[6]" ]
set_property PACKAGE_PIN   J19   [ get_ports "ddr4_adr[7]" ]
set_property PACKAGE_PIN   J21   [ get_ports "ddr4_adr[8]" ]
set_property PACKAGE_PIN   F20   [ get_ports "ddr4_adr[9]" ]
set_property PACKAGE_PIN   L20   [ get_ports "ddr4_adr[10]" ]
set_property PACKAGE_PIN   M20   [ get_ports "ddr4_adr[11]" ]
set_property PACKAGE_PIN   N20   [ get_ports "ddr4_adr[12]" ]
set_property PACKAGE_PIN   K19   [ get_ports "ddr4_adr[13]" ]
set_property PACKAGE_PIN   J22   [ get_ports "ddr4_adr[14]" ]
set_property PACKAGE_PIN   H19  [ get_ports "ddr4_adr[15]" ]
set_property PACKAGE_PIN   H20   [ get_ports "ddr4_adr[16]" ]

set_property PACKAGE_PIN K22 [ get_ports "ddr4_ba[0]" ]
set_property PACKAGE_PIN F19 [ get_ports "ddr4_ba[1]" ]
set_property PACKAGE_PIN F22 [ get_ports "ddr4_bg[0]" ]


set_property PACKAGE_PIN G22 [ get_ports "ddr4_ck_t[0]" ]
set_property PACKAGE_PIN G21 [ get_ports "ddr4_ck_c[0]" ]
set_property PACKAGE_PIN D21 [ get_ports "ddr4_cke[0]" ]

set_property PACKAGE_PIN K20 [ get_ports "ddr4_act_n" ]

set_property PACKAGE_PIN F23 [ get_ports "ddr4_reset_n" ]
set_property PACKAGE_PIN K21 [ get_ports "ddr4_odt[0]" ]
set_property PACKAGE_PIN N19 [ get_ports "ddr4_cs_n[0]" ]

set_property PACKAGE_PIN G23 [ get_ports "ddr4_dqs_c[0]" ]
set_property PACKAGE_PIN H23 [ get_ports "ddr4_dqs_t[0]" ]
set_property PACKAGE_PIN K24 [ get_ports "ddr4_dqs_c[1]" ]
set_property PACKAGE_PIN L24 [ get_ports "ddr4_dqs_t[1]" ]
set_property PACKAGE_PIN B26 [ get_ports "ddr4_dqs_c[2]" ]
set_property PACKAGE_PIN B25 [ get_ports "ddr4_dqs_t[2]" ]
set_property PACKAGE_PIN E27 [ get_ports "ddr4_dqs_c[3]" ]
set_property PACKAGE_PIN E26 [ get_ports "ddr4_dqs_t[3]" ]
set_property PACKAGE_PIN A32 [ get_ports "ddr4_dqs_c[4]" ]
set_property PACKAGE_PIN B31 [ get_ports "ddr4_dqs_t[4]" ]
set_property PACKAGE_PIN F30 [ get_ports "ddr4_dqs_c[5]" ]
set_property PACKAGE_PIN G30 [ get_ports "ddr4_dqs_t[5]" ]
set_property PACKAGE_PIN A40 [ get_ports "ddr4_dqs_c[6]" ]
set_property PACKAGE_PIN A39 [ get_ports "ddr4_dqs_t[6]" ]
set_property PACKAGE_PIN C34 [ get_ports "ddr4_dqs_c[7]" ]
set_property PACKAGE_PIN D34 [ get_ports "ddr4_dqs_t[7]" ]


set_property PACKAGE_PIN K27 [ get_ports "ddr4_dm_n[0]" ]
set_property PACKAGE_PIN P26 [ get_ports "ddr4_dm_n[1]" ]
set_property PACKAGE_PIN C28 [ get_ports "ddr4_dm_n[2]" ]
set_property PACKAGE_PIN G26 [ get_ports "ddr4_dm_n[3]" ]
set_property PACKAGE_PIN E29 [ get_ports "ddr4_dm_n[4]" ]
set_property PACKAGE_PIN K29 [ get_ports "ddr4_dm_n[5]" ]
set_property PACKAGE_PIN C36 [ get_ports "ddr4_dm_n[6]" ]
set_property PACKAGE_PIN E32 [ get_ports "ddr4_dm_n[7]" ]





set_property PACKAGE_PIN G25 [ get_ports "ddr4_dq[0]" ]
set_property PACKAGE_PIN J24 [ get_ports "ddr4_dq[1]" ]
set_property PACKAGE_PIN H25 [ get_ports "ddr4_dq[2]" ]
set_property PACKAGE_PIN J26 [ get_ports "ddr4_dq[3]" ]
set_property PACKAGE_PIN H24 [ get_ports "ddr4_dq[4]" ]
set_property PACKAGE_PIN K26 [ get_ports "ddr4_dq[5]" ]
set_property PACKAGE_PIN H26 [ get_ports "ddr4_dq[6]" ]
set_property PACKAGE_PIN J23 [ get_ports "ddr4_dq[7]" ]
set_property PACKAGE_PIN M25 [ get_ports "ddr4_dq[8]" ]
set_property PACKAGE_PIN M23 [ get_ports "ddr4_dq[9]" ]
set_property PACKAGE_PIN L25 [ get_ports "ddr4_dq[10]" ]
set_property PACKAGE_PIN L23 [ get_ports "ddr4_dq[11]" ]
set_property PACKAGE_PIN N24 [ get_ports "ddr4_dq[12]" ]
set_property PACKAGE_PIN N23 [ get_ports "ddr4_dq[13]" ]
set_property PACKAGE_PIN N25 [ get_ports "ddr4_dq[14]" ]
set_property PACKAGE_PIN P23 [ get_ports "ddr4_dq[15]" ]
set_property PACKAGE_PIN A28 [ get_ports "ddr4_dq[16]" ]
set_property PACKAGE_PIN A24 [ get_ports "ddr4_dq[17]" ]
set_property PACKAGE_PIN B27 [ get_ports "ddr4_dq[18]" ]
set_property PACKAGE_PIN C25 [ get_ports "ddr4_dq[19]" ]
set_property PACKAGE_PIN A27 [ get_ports "ddr4_dq[20]" ]
set_property PACKAGE_PIN C26 [ get_ports "ddr4_dq[21]" ]
set_property PACKAGE_PIN A25 [ get_ports "ddr4_dq[22]" ]
set_property PACKAGE_PIN C24 [ get_ports "ddr4_dq[23]" ]
set_property PACKAGE_PIN F27 [ get_ports "ddr4_dq[24]" ]
set_property PACKAGE_PIN F25 [ get_ports "ddr4_dq[25]" ]
set_property PACKAGE_PIN D27 [ get_ports "ddr4_dq[26]" ]
set_property PACKAGE_PIN E25 [ get_ports "ddr4_dq[27]" ]
set_property PACKAGE_PIN F28 [ get_ports "ddr4_dq[28]" ]
set_property PACKAGE_PIN F24 [ get_ports "ddr4_dq[29]" ]
set_property PACKAGE_PIN D28 [ get_ports "ddr4_dq[30]" ]
set_property PACKAGE_PIN E24 [ get_ports "ddr4_dq[31]" ]
set_property PACKAGE_PIN D31 [ get_ports "ddr4_dq[32]" ]
set_property PACKAGE_PIN A29 [ get_ports "ddr4_dq[33]" ]
set_property PACKAGE_PIN C30 [ get_ports "ddr4_dq[34]" ]
set_property PACKAGE_PIN A30 [ get_ports "ddr4_dq[35]" ]
set_property PACKAGE_PIN E31 [ get_ports "ddr4_dq[36]" ]
set_property PACKAGE_PIN C29 [ get_ports "ddr4_dq[37]" ]
set_property PACKAGE_PIN C31 [ get_ports "ddr4_dq[38]" ]
set_property PACKAGE_PIN B30 [ get_ports "ddr4_dq[39]" ]
set_property PACKAGE_PIN F32 [ get_ports "ddr4_dq[40]" ]
set_property PACKAGE_PIN G28 [ get_ports "ddr4_dq[41]" ]
set_property PACKAGE_PIN H30 [ get_ports "ddr4_dq[42]" ]
set_property PACKAGE_PIN J28 [ get_ports "ddr4_dq[43]" ]
set_property PACKAGE_PIN J30 [ get_ports "ddr4_dq[44]" ]
set_property PACKAGE_PIN H28 [ get_ports "ddr4_dq[45]" ]
set_property PACKAGE_PIN F31 [ get_ports "ddr4_dq[46]" ]
set_property PACKAGE_PIN F29 [ get_ports "ddr4_dq[47]" ]
set_property PACKAGE_PIN C42 [ get_ports "ddr4_dq[48]" ]
set_property PACKAGE_PIN A38 [ get_ports "ddr4_dq[49]" ]
set_property PACKAGE_PIN B40 [ get_ports "ddr4_dq[50]" ]
set_property PACKAGE_PIN B37 [ get_ports "ddr4_dq[51]" ]
set_property PACKAGE_PIN B42 [ get_ports "ddr4_dq[52]" ]
set_property PACKAGE_PIN B36 [ get_ports "ddr4_dq[53]" ]
set_property PACKAGE_PIN B41 [ get_ports "ddr4_dq[54]" ]
set_property PACKAGE_PIN A37 [ get_ports "ddr4_dq[55]" ]
set_property PACKAGE_PIN C33 [ get_ports "ddr4_dq[56]" ]
set_property PACKAGE_PIN A35 [ get_ports "ddr4_dq[57]" ]
set_property PACKAGE_PIN D33 [ get_ports "ddr4_dq[58]" ]
set_property PACKAGE_PIN B33 [ get_ports "ddr4_dq[59]" ]
set_property PACKAGE_PIN B32 [ get_ports "ddr4_dq[60]" ]
set_property PACKAGE_PIN A34 [ get_ports "ddr4_dq[61]" ]
set_property PACKAGE_PIN B35 [ get_ports "ddr4_dq[62]" ]
set_property PACKAGE_PIN A33 [ get_ports "ddr4_dq[63]" ]

